export const ROLES = {
    DEFAULT: "PHYSICIAN",
    ATTENDING_PHYSICIAN: "PHYSICIAN",
    LAB_PHYSICIAN: "LAB_PHYSICIAN",
    IMAGING_PHYSICIAN: "IMAGE_PHYSICIAN",
    GENERAL_PHYSICIAN: "GENERAL_PHYSICIAN",   // BÁC SĨ ĐA KHOA
    OBSTETRIC_PHYSICIAN: "OBSTETRIC_PHYSICIAN",  // BÁC SĨ SẢN
    OPHTHALMOLOGY_PHYSICIAN: "OPHTHALMOLOGY_PHYSICIAN",  // BÁC SĨ NHÃN
    CARDIOLOGY_PHYSICIAN: "CARDIOLOGY_PHYSICIAN",  // BÁC SĨ TIM MẠCH
    INTERNAL_PHYSICIAN: "INTERNAL_PHYSICIAN",  // BÁC SĨ NỘI
    ENT_PHYSICIAN: "ENT_PHYSICIAN",  // BÁC SĨ TAI MẠCH
    PEDIATRIC_PHYSICIAN: "PEDIATRIC_PHYSICIAN",  // BÁC SĨ NHI
    DERMATOLOGY_PHYSICIAN: "DERMATOLOGY_PHYSICIAN",  // BÁC SĨ DA LIỄU
    DENTAL_PHYSICIAN: "DENTAL_PHYSICIAN",  // BÁC SĨ NHA KHOA
    NEUROLOGY_PHYSICIAN: "NEUROLOGY_PHYSICIAN",  // BÁC SĨ THẦN KINH
    SURGICAL_PHYSICIAN: "SURGICAL_PHYSICIAN",  // BÁC SĨ PHẪU THUẬT
    BIOCHEMISTRY_PHYSICIAN: "BIOCHEMISTRY_PHYSICIAN",  // BÁC SĨ HÓA SINH
    HEMATOLOGY_PHYSICIAN: "HEMATOLOGY_PHYSICIAN",  // BÁC SĨ HUYẾT HỌC
    CLINICAL_HEMATOLOGY_PHYSICIAN: "CLINICAL_HEMATOLOGY_PHYSICIAN",  // BÁC SĨ HUYẾT HỌC LÂM SÀNG
    NEURO_PHYSIOLOGY_PHYSICIAN: "NEURO_PHYSIOLOGY_PHYSICIAN",  // BÁC SĨ SINH LÝ THẦN KINH
    RESPIRATORY_PHYSIOLOGY_PHYSICIAN: "RESPIRATORY_PHYSIOLOGY_PHYSICIAN",  // BÁC SĨ SINH LÝ HÔ HẤP
    RADIOLOGY_PHYSICIAN: "RADIOLOGY_PHYSICIAN",  // BÁC SĨ X-quang
}

export const labPhysician: string[] = [
    ROLES.LAB_PHYSICIAN,
    ROLES.BIOCHEMISTRY_PHYSICIAN,
    ROLES.HEMATOLOGY_PHYSICIAN,
    ROLES.CLINICAL_HEMATOLOGY_PHYSICIAN,
]

export const imagingPhysician: string[] = [
    ROLES.IMAGING_PHYSICIAN,
    ROLES.RADIOLOGY_PHYSICIAN,
]