export const SERVICE_TYPES = {
    GENERAL_CONSULTATION: 'GENERAL CONSULTATION',
    SPECIALIST_CONSULTATION: 'SPECIALIST CONSULTATION',
    LABORATORY_TEST: 'LABORATORY TEST',
    IMAGING_SCAN: 'IMAGING TEST',
};