export interface LoginResponse {
    identifier: number,
    name: string,
    telecom: string | null,
    email: string | null,
    gender: boolean,
    birthDate: Date,
    photo: string | null,
    address: string,
    active: boolean,
    startDate: Date,
    endDate: Date,
    specialtyIdentifier: number,
    role: string,
    token: string,
}